services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./docker-volumes/redis:/data
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    env_file:
      - ./.env
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
